datadrivencz/proxima-platform

- cassandra/src/main/java/cz/o2/proxima/storage/cassandra/CassandraDBAccessor.java
- cassandra/src/main/java/cz/o2/proxima/storage/cassandra/CassandraLogObservable.java
- cassandra/src/main/java/cz/o2/proxima/storage/cassandra/CassandraRandomReader.java
- cassandra/src/main/java/cz/o2/proxima/storage/cassandra/CassandraWriter.java
- cassandra/src/main/java/cz/o2/proxima/storage/cassandra/DateToLongConverter.java
- cassandra/src/main/java/cz/o2/proxima/storage/cassandra/StringConverter.java
- cassandra/src/test/java/cz/o2/proxima/storage/cassandra/CassandraDBAccessorTest.java
- core/src/main/java/cz/o2/proxima/repository/Constants.java
- core/src/main/java/cz/o2/proxima/repository/Context.java
- core/src/main/java/cz/o2/proxima/repository/Repository.java
- core/src/main/java/cz/o2/proxima/storage/AbstractStorage.java
- core/src/main/java/cz/o2/proxima/storage/DataAccessor.java
- core/src/main/java/cz/o2/proxima/storage/stdout/StdoutStorage.java
- core/src/test/java/cz/o2/proxima/storage/InMemBulkStorage.java
- core/src/test/java/cz/o2/proxima/storage/InMemStorage.java
- gcloud-storage/src/main/java/cz/o2/proxima/gcloud/storage/GCloudLogObservable.java
- gcloud-storage/src/main/java/cz/o2/proxima/gcloud/storage/GCloudStorageAccessor.java
- hbase/hbase-bindings/src/main/java/cz/o2/proxima/storage/hbase/HBaseDataAccessor.java
- hbase/hbase-bindings/src/main/java/cz/o2/proxima/storage/hbase/HBaseLogObservable.java
- hbase/hbase-hbase/src/test/java/cz/o2/proxima/storage/hbase/HBaseLogObservableTest.java
- hdfs/src/main/java/cz/o2/proxima/storage/hdfs/HdfsDataAccessor.java
- http/src/main/java/cz/o2/proxima/storage/http/HttpWriter.java
- kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaAccessor.java
- kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaLogReader.java
- kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaStreamElement.java
- kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaWriter.java
- kafka/src/test/java/cz/o2/proxima/storage/kafka/LocalKafkaCommitLogDescriptor.java
- kafka/src/test/java/cz/o2/proxima/storage/kafka/LocalKafkaCommitLogDescriptorTest.java
> [proxima-core] #35 use executor for running observers

- README.md
- io-kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaLogObserver.java
- scripts/shade-grpc-services.sh
> Fix build on MacOsx

- core/pom.xml
- core/src/main/java/cz/o2/proxima/source/BatchSource.java
- core/src/main/java/cz/o2/proxima/source/BoundedStreamSource.java
- core/src/main/java/cz/o2/proxima/source/DatasetUtils.java
- core/src/main/java/cz/o2/proxima/source/UnboundedStreamSource.java
- core/src/main/java/cz/o2/proxima/view/input/DataSourceUtils.java
- core/src/test/java/cz/o2/proxima/source/BatchSourceTest.java
- core/src/test/java/cz/o2/proxima/source/BoundedSourceTest.java
- core/src/test/java/cz/o2/proxima/source/BoundedStreamSourceTest.java
- core/src/test/java/cz/o2/proxima/storage/InMemBulkStorage.java
- core/src/test/java/cz/o2/proxima/storage/InMemStorage.java
- core/src/test/java/cz/o2/proxima/storage/InMemStorageTest.java
- core/src/test/resources/test-reference.conf
- ingest-client/src/main/java/cz/o2/proxima/client/IngestClient.java
- ingest-server/src/main/java/cz/o2/proxima/server/IngestServer.java
- ingest-server/src/test/java/cz/o2/proxima/server/IngestServiceTest.java
- io-gcloud-storage/src/main/java/cz/o2/proxima/gcloud/storage/BulkGCloudStorageWriter.java
- io-gcloud-storage/src/test/java/cz/o2/proxima/gcloud/storage/BulkGCloudStorageWriterTest.java
- io-http/src/main/java/cz/o2/proxima/storage/http/WebsocketReader.java
- io-kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaAccessor.java
- io-kafka/src/main/java/cz/o2/proxima/storage/kafka/KafkaLogReader.java
- io-kafka/src/main/java/cz/o2/proxima/storage/kafka/OffsetCommitter.java
- io-kafka/src/test/java/cz/o2/proxima/storage/kafka/LocalKafkaCommitLogDescriptor.java
- tools/src/main/java/cz/o2/proxima/tools/groovy/Console.java
> Resolve bugs and vulnerabilities reported by sonar

- scheme/avro/src/main/java/cz/o2/proxima/scheme/avro/AvroSerializerFactory.java
- scheme/confluent/src/main/java/cz/o2/proxima/scheme/confluent/SchemaRegistrySerializerFactory.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/JsonProtoSerializerFactory.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactory.java
Serialization of factory isn't required so we can make it static
> Improve serializers serialization.

- core/src/main/java/cz/o2/proxima/storage/UriUtil.java
- core/src/test/java/cz/o2/proxima/storage/UriUtilTest.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/Util.java
- direct/io-hbase-bindings/src/test/java/cz/o2/proxima/direct/hbase/UtilTest.java
- direct/io-hbase/src/test/java/cz/o2/proxima/direct/hbase/HBaseLogObservableTest.java
- direct/io-hbase/src/test/java/cz/o2/proxima/direct/hbase/HBaseWriterTest.java
- direct/io-hbase/src/test/java/cz/o2/proxima/direct/hbase/HbaseTestUtil.java
- direct/io-hbase/src/test/java/cz/o2/proxima/direct/hbase/RandomHBaseReaderTest.java
- scheme/confluent/src/main/java/cz/o2/proxima/scheme/confluent/SchemaRegistryValueSerializer.java
> Allow to specify zookeeper path for hbase in url

- direct/ingest-client/README.md
- direct/ingest-client/src/main/java/cz/o2/proxima/client/IngestClient.java
- direct/ingest-client/src/test/java/cz/o2/proxima/client/IngestClientTest.java
- direct/ingest-client/src/test/java/cz/o2/proxima/client/RetrieveServiceTest.java
- direct/rpc/src/main/proto/rpc.proto
~Currently I have no idea how to test synchronous calls. I'll try to look on it more deeply Tomorrow.~
Tests added, i'm still not sure about change in last commit - added syntactic sugar. I would like to here other opinion on that.
> Allow to call RPC listAttributes from java IngestClient + typos

- maven/src/main/java/cz/o2/proxima/generator/ModelGenerator.java
- maven/src/main/java/cz/o2/proxima/maven/CompileMojo.java
- maven/src/test/java/cz/o2/proxima/generator/ModelGeneratorTest.java
Reuse File objects from gradle plugin.
> [proxima-maven] Model generator constructor receives File objects.

- core/src/main/java/cz/o2/proxima/repository/AttributeFamilyDescriptor.java
- core/src/main/java/cz/o2/proxima/repository/ConsumerNameFactory.java
- core/src/main/java/cz/o2/proxima/repository/DefaultConsumerNameFactory.java
- core/src/test/java/cz/o2/proxima/repository/AttributeFamilyDescriptorTest.java
- core/src/test/java/cz/o2/proxima/repository/ConfigRepositoryTest.java
- core/src/test/java/cz/o2/proxima/repository/DefaultConsumerNameFactoryTest.java
- core/src/test/resources/test-reference.conf
- direct/ingest-server/src/main/java/cz/o2/proxima/server/IngestServer.java
- direct/ingest-server/src/main/java/cz/o2/proxima/server/ReplicationController.java
- direct/ingest-server/src/test/java/cz/o2/proxima/server/RetrieveServiceTest.java
> Make consumer name configurable

- core/src/main/java/cz/o2/proxima/repository/ConfigRepository.java
- core/src/main/java/cz/o2/proxima/repository/RepositoryFactory.java
- core/src/test/java/cz/o2/proxima/repository/ConfigRepositoryTest.java
Added test for config udpate after serialization
> [proxima-core] test deserializing of updated config

- direct/core/src/main/java/cz/o2/proxima/direct/core/DataAccessor.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/DirectDataOperator.java
- direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaAccessor.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/KafkaAccessorTest.java
…Kafka topics (default method in DataAccessor)
> [proxima-direct,proxima-direct-io-kafka] Added isAceptible check for Kafka topics

- direct/io-gcloud-storage/src/main/java/cz/o2/proxima/direct/gcloud/storage/BulkGCloudStorageWriter.java
- direct/io-gcloud-storage/src/test/java/cz/o2/proxima/direct/gcloud/storage/BulkGCloudStorageWriterTest.java
> [proxima-direct-io-gcloud-storage] Don't initialize writer before writing

- direct/io-bigtable/pom.xml
- direct/io-pubsub/pom.xml
- maven/pom.xml
Fixes `mvn clean compile` command.
> Fix maven build lifecycle.

- beam/core/src/main/java/cz/o2/proxima/beam/transforms/BufferUntilCheckpoint.java
- beam/core/src/main/java/cz/o2/proxima/beam/transforms/StreamElementFilter.java
- beam/core/src/test/java/cz/o2/proxima/beam/transforms/BufferUntilCheckpointTest.java
- beam/core/src/test/java/cz/o2/proxima/beam/transforms/ExtractKeyToKvTest.java
- beam/core/src/test/java/cz/o2/proxima/beam/transforms/StreamElementFilterTest.java
This is the first step of integration typed StreamElement into beam-core.
> [Beam-core]: Introduce StreamElementFilter transforms

- .travis.yml
- pom.xml
> [infra]: use openjdk11 for sonar scanner

- direct/core/src/main/java/cz/o2/proxima/direct/commitlog/CommitLogReaders.java
- direct/core/src/test/java/cz/o2/proxima/commitlog/CommitLogReadersTest.java
> [direct-core] CommitLog reader should not resolve partitions during instantiation

- core/src/main/java/cz/o2/proxima/repository/AttributeDescriptor.java
- core/src/main/java/cz/o2/proxima/scheme/AttributeValueType.java
- core/src/main/java/cz/o2/proxima/scheme/BytesSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/FloatSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/IntSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/LongSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/SchemaDescriptors.java
- core/src/main/java/cz/o2/proxima/scheme/StringUtf8Serializer.java
- core/src/main/java/cz/o2/proxima/scheme/ValueSerializer.java
- core/src/test/java/cz/o2/proxima/repository/AttributeFamilyDescriptorTest.java
- core/src/test/java/cz/o2/proxima/scheme/BytesSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/FloatSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/IntSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/LongSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/SchemaDescriptorsTest.java
- core/src/test/java/cz/o2/proxima/scheme/StringUtf8SerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/ValueSerializerTest.java
- scheme/avro/src/main/java/cz/o2/proxima/scheme/avro/AvroSerializerFactory.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactory.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/utils/ProtoUtils.java
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactoryTest.java
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/utils/ProtoUtilsTest.java
- scheme/proto/src/test/proto/scheme.proto
Implements https://github.com/O2-Czech-Republic/proxima-platform/issues/187
> Introduce attribute value schema inspection API.

- beam/io-pubsub/pom.xml
- direct/io-gcloud-storage/pom.xml
- direct/io-pubsub/pom.xml
Co-authored-by: dmvk <dmvk@apache.org>
> Shade old gson

- direct/core/src/main/java/cz/o2/proxima/direct/commitlog/RetryableLogObserver.java
- direct/core/src/test/java/cz/o2/proxima/direct/commitlog/RetryableLogObserverTest.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptorTest.java
This reverts commit ca3663253141ecb54dd352dfcfa0e65936c5672c.
> Revert "[proxima-direct-core] fix RetryableLogObserver contract"

- core/src/main/java/cz/o2/proxima/scheme/BytesSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/FloatSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/IntSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/LongSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/SchemaDescriptors.java
- core/src/main/java/cz/o2/proxima/scheme/StringUtf8Serializer.java
- core/src/test/java/cz/o2/proxima/repository/AttributeFamilyDescriptorTest.java
- core/src/test/java/cz/o2/proxima/scheme/AlwaysFailSchemeParser.java
- core/src/test/java/cz/o2/proxima/scheme/BytesSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/FloatSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/SchemaDescriptorsTest.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactory.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/utils/ProtoUtils.java
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/utils/ProtoUtilsTest.java
- scheme/proto/src/test/proto/scheme.proto
Extracting changes into separate PR.
> [proxima-core] Refactor Attribute schema API to be more clean and simple to use.

- core/src/main/java/cz/o2/proxima/functional/UnaryFunction.java
- core/src/main/java/cz/o2/proxima/scheme/AttributeValueAccessor.java
- core/src/main/java/cz/o2/proxima/scheme/AttributeValueAccessors.java
- core/src/main/java/cz/o2/proxima/scheme/BytesSerializer.java
- core/src/main/java/cz/o2/proxima/scheme/ValueSerializer.java
- core/src/test/java/cz/o2/proxima/scheme/AttributeValueAccessorsTest.java
- core/src/test/java/cz/o2/proxima/scheme/BytesSerializerTest.java
- core/src/test/java/cz/o2/proxima/scheme/ValueSerializerTest.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoMessageValueAccessor.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactory.java
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoMessageValueAccessorTest.java
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactoryTest.java
Introduce attribute value accessors which allows manipulation with attribute values.
> Refactored attribute value accessors

- direct/io-blob/src/main/java/cz/o2/proxima/direct/blob/BlobPath.java
- direct/io-gcloud-storage/src/main/java/cz/o2/proxima/direct/gcloud/storage/GCloudBlobPath.java
- direct/io-s3/src/main/java/cz/o2/proxima/direct/s3/S3BlobPath.java
`S3BlobPath(context=cz.o2.proxima.direct.core.Context@46568c32)` is not so much useful : )
> Make toString on Blobs consistent

- scheme/pom.xml
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactory.java
- scheme/proto/src/main/proto/transactions.proto
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactoryTest.java
- scheme/proto/src/test/resources/test-transactions-proto.conf
This closes O2-Czech-Republic#202
> #202 add proto transaction serializer

- direct/core/src/main/java/cz/o2/proxima/direct/randomaccess/KeyValue.java
- direct/core/src/main/java/cz/o2/proxima/direct/randomaccess/RandomAccessReader.java
- direct/core/src/test/java/cz/o2/proxima/direct/randomaccess/KeyValueTest.java
- direct/io-bigtable/src/main/java/cz/o2/proxima/direct/bigtable/BigTableStorage.java
- direct/io-hbase-bindings/pom.xml
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/HBaseDataAccessor.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/HBaseLogReader.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/HBaseWriter.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/InternalSerializer.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/InternalSerializers.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/RandomHBaseReader.java
- direct/io-hbase-bindings/src/main/proto/v2_serializer.proto
- direct/io-hbase-bindings/src/test/java/cz/o2/proxima/direct/hbase/HBaseWriterTest.java
>  O2-Czech-Republic#211 implement HBase storage v2 using sequentialId

- direct/core/src/main/java/cz/o2/proxima/direct/core/AbstractOnlineAttributeWriter.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/DirectDataOperator.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/OnlineAttributeWriter.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionResourceManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/test/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriterTest.java
> [proxima-direct-core] #200 introduce TransactionalOnlineAttributeWriter

- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionResourceManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/main/java/cz/o2/proxima/direct/view/LocalCachedPartitionedView.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> [proxima-direct-transcation-manager] #214 support explicit ROLLBACK

- .github/autolabeler.yml
- flink/core/license-header-spotless.txt
- flink/core/license-header.txt
- flink/core/pom.xml
- flink/core/src/main/java/cz/o2/proxima/flink/core/CommitLogSourceFunction.java
- flink/core/src/test/java/cz/o2/proxima/flink/core/CommitLogSourceFunctionTest.java
- flink/core/src/test/java/cz/o2/proxima/flink/core/TestSourceContext.java
- flink/license-header-spotless.txt
- flink/license-header.txt
- flink/pom.xml
- io/io-pubsub/pom.xml
- pom.xml
Basic implementation of commit log source function.
**Implemented Features**
- Source that observers all partitions from OLDEST position.
- Checkpointing & Restore
- Rescale from snapshot
**Missing Features (TBD in future PRs):**
- Configurable position & partitions
- DataOperator
> [flink-core] Introduce CommitLogSourceFunction.

- direct/core/src/main/java/cz/o2/proxima/direct/core/DirectDataOperator.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/DelegatingCachedView.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionResourceManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionalCachedView.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/test/java/cz/o2/proxima/direct/transaction/TransactionResourceManagerTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/transaction/TransactionalCachedViewTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriterTest.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactoryTest.java
> O2-Czech-Republic#201 transactional cached view rebased

- direct/core/src/main/java/cz/o2/proxima/direct/view/CachedView.java
- direct/core/src/main/java/cz/o2/proxima/direct/view/LocalCachedPartitionedView.java
- direct/core/src/main/java/cz/o2/proxima/direct/view/TimeBoundedVersionedCache.java
- direct/core/src/test/java/cz/o2/proxima/direct/view/LocalCachedPartitionedViewTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/view/TimeBoundedVersionedCacheTest.java
> [proxima-direct-core] O2-Czech-Republic#221 TTL for LocalCachedPartitionedView

- beam/tools/src/main/java/cz/o2/proxima/beam/tools/groovy/BeamStream.java
- beam/tools/src/test/java/cz/o2/proxima/beam/tools/groovy/BeamStreamTest.java
> [proxima-beam-tools] O2-Czech-Republic#233 fix flakiness of ReduceValueStateByKey

- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionResourceManager.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
> [proxima-direct] O2-Czech-Republic#215 allow specifying explicit cleanup interval

- direct/core/src/main/java/cz/o2/proxima/direct/transaction/ServerTransactionManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionResourceManager.java
- direct/ingest-server/src/main/java/cz/o2/proxima/server/IngestServer.java
- direct/ingest-server/src/main/java/cz/o2/proxima/server/transaction/TransactionContext.java
- direct/ingest-server/src/test/java/cz/o2/proxima/server/IngestServiceTest.java
- direct/ingest-server/src/test/java/cz/o2/proxima/server/transaction/TransactionsTest.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
> [proxima-ingest-server-grpc] #239 correctly cleanup transactions on timeout

- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/DefaultCqlFactory.java
- direct/io-cassandra/src/test/java/cz/o2/proxima/direct/cassandra/DefaultCqlFactoryTest.java
> [proxima-direct-io-cassandra] O2-Czech-Republic#241 fix escape of column name in scanPartition

- .github/mvn-build-changed-modules.sh
- .github/workflows/build.yml
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> [proxima-transaction-manager] O2-Czech-Republic#245 add output attributes to conflict verification

- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraDBAccessor.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraLogReader.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraRandomReader.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraWriter.java
- direct/io-cassandra/src/test/java/cz/o2/proxima/direct/cassandra/CassandraDBAccessorTest.java
> [proxima-direct-io-cassandra] O2-Czech-Republic#242 add Cluster and Session management per URI authority

- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraDBAccessor.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraLogReader.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraRandomReader.java
> O2-Czech-Republic#244 allow specifying consistency level

- .github/workflows/mvn.sh
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraDBAccessor.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraLogReader.java
- direct/io-cassandra/src/test/java/cz/o2/proxima/direct/cassandra/CassandraDBAccessorTest.java
> [proxima-direct-io-cassandra] #248 fix closing of Cluster

- direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaLogReader.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptor.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptorTest.java
> [proxima-direct-io-kafka] O2-Czech-Republic#243 fix stopAtCurrent with frequent log-roll

- direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaLogReader.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptor.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptorTest.java
> [proxima-direct-io-kafka] O2-Czech-Republic#251 fix deadlock when first poll throws exception

- direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaLogReader.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptor.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptorTest.java
> [proxima-direct-io-kafka] O2-Czech-Republic#236 handle RebalanceInProgressException

- utils-zookeeper/src/main/java/cz/o2/proxima/utils/zookeeper/ZKGlobalWatermarkTracker.java
> [utils-zookeeper] O2-Czech-Republic#258 fix ZK connect timeouts

- beam/tools/pom.xml
- direct/io-hbase-bindings/pom.xml
[proxima-beam-tools] exclude log4j12 from hadoop
> [proxima-direct-io-hbase-bindings] exclude log4j12 from hadoop

- beam/tools/pom.xml
- direct/io-bigtable/pom.xml
- direct/io-bigtable/src/test/java/cz/o2/proxima/direct/bigtable/BigTableStorageTest.java
- direct/io-bulkfs-parquet/pom.xml
- direct/io-hadoop/pom.xml
- direct/io-hbase-bindings/pom.xml
- direct/io-hbase/pom.xml
- direct/io-hdfs/pom.xml
- utils-zookeeper/pom.xml
> [io-hbase-bindings] O2-Czech-Republic#260 fix NoClassDefFoundError in log4j

- beam/tools/src/main/java/cz/o2/proxima/beam/tools/groovy/BeamStreamProvider.java
- beam/tools/src/test/java/cz/o2/proxima/beam/tools/groovy/BeamStreamProviderTest.java
- tools/src/main/java/cz/o2/proxima/tools/groovy/Console.java
- tools/src/main/java/cz/o2/proxima/tools/groovy/ToolsClassLoader.java
- tools/src/test/java/cz/o2/proxima/tools/groovy/GroovyEnvTest.java
> [proxima-tools] O2-Czech-Republic#264 add additional @Grab'd jars to runners

- beam/pom.xml
- beam/tools/pom.xml
- beam/tools/src/test/java/cz/o2/proxima/beam/tools/groovy/BeamGroovyEnvTest.java
This closes O2-Czech-Republic#267
> [proxima-beam] bump scala to 2.12, fix O2-Czech-Republic#267

- core/src/test/resources/test-transactions.conf
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/test/java/cz/o2/proxima/direct/transaction/TransactionUniqueConstraintValidator.java
- direct/core/src/test/java/cz/o2/proxima/direct/transaction/TransactionValidatorTest.java
- direct/core/src/test/resources/test-validator.conf
This closes O2-Czech-Republic#269
> [proxima-direct-core] O2-Czech-Republic#269 add TransactionValidator

- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/main/java/cz/o2/proxima/direct/transform/TransformationObserver.java
- direct/core/src/test/java/cz/o2/proxima/direct/transform/TransformationObserverTest.java
This closes O2-Czech-Republic#271
> [proxima-direct-core] O2-Czech-Republic#271 handle TransactionRejectedRuntimeException in Contextual transforms

- tools/src/main/java/cz/o2/proxima/tools/io/ConsoleRandomReader.java
- tools/src/main/resources/class-entitydesc.ftlh
- tools/src/test/java/cz/o2/proxima/tools/groovy/GroovyEnvTest.java
> [proxima-tools] O2-Czech-Republic#278 add listPrefix to console

- direct/io-elasticsearch/src/main/java/cz/o2/proxima/direct/elasticsearch/ElasticsearchAccessor.java
- direct/io-elasticsearch/src/test/java/cz/o2/proxima/direct/elasticsearch/ElasticsearchAccessorTest.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/HBaseDataAccessor.java
- direct/io-hbase-bindings/src/test/java/cz/o2/proxima/direct/hbase/HBaseDataAccessorTest.java
- direct/io-http/src/main/java/cz/o2/proxima/direct/http/HttpAccessor.java
- direct/io-http/src/test/java/cz/o2/proxima/direct/http/HttpAccessorTest.java
> [direct-io] O2-Czech-Republic#282 fix serializability of DataAccessors

- beam/tools/src/main/java/cz/o2/proxima/beam/tools/groovy/BeamStream.java
- beam/tools/src/test/java/cz/o2/proxima/beam/tools/groovy/BeamStreamTest.java
- direct/core/src/main/java/cz/o2/proxima/direct/transaction/TransactionResourceManager.java
> 283 console writer handling transactions

- beam/tools/src/main/java/cz/o2/proxima/beam/tools/groovy/BeamStream.java
- tools/src/main/java/cz/o2/proxima/tools/groovy/Stream.java
- tools/src/test/java/cz/o2/proxima/tools/groovy/StreamTest.java
> [proxima-tools] O2-Czech-Republic#285 add Stream#reshuffle()

- direct/core/src/main/java/cz/o2/proxima/direct/batch/TerminationContext.java
- direct/core/src/main/java/cz/o2/proxima/direct/randomaccess/RandomAccessReader.java
- direct/core/src/test/java/cz/o2/proxima/direct/batch/TerminationContextTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/randomaccess/RandomAccessReaderTest.java
- direct/ingest-client/src/test/java/cz/o2/proxima/client/RetrieveServiceTest.java
- direct/ingest-server/src/main/java/cz/o2/proxima/server/RetrieveService.java
- direct/ingest-server/src/test/java/cz/o2/proxima/server/RetrieveServiceTest.java
- direct/rpc/src/main/proto/rpc.proto
> [ingest-server] O2-Czech-Republic#284 add multiget method to rpc

- beam/core/src/main/java/cz/o2/proxima/beam/direct/io/BatchLogRead.java
- beam/core/src/main/java/cz/o2/proxima/beam/direct/io/BlockingQueueLogObserver.java
- beam/core/src/test/java/cz/o2/proxima/beam/direct/io/BatchLogReadTest.java
- core/src/main/java/cz/o2/proxima/storage/watermark/GlobalWatermarkThroughputLimiter.java
- core/src/test/java/cz/o2/proxima/storage/watermark/GlobalWatermarkThroughputLimiterTest.java
- direct/core/src/main/java/cz/o2/proxima/direct/batch/TerminationContext.java
- direct/core/src/test/java/cz/o2/proxima/direct/batch/TerminationContextTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/storage/InMemBulkStorage.java
- direct/core/src/test/java/cz/o2/proxima/direct/storage/InMemStorage.java
- direct/core/src/test/java/cz/o2/proxima/direct/storage/ListBatchReader.java
- direct/core/src/test/java/cz/o2/proxima/direct/storage/ListBatchReaderTest.java
- direct/io-blob/src/main/java/cz/o2/proxima/direct/blob/BlobLogReader.java
- direct/io-blob/src/test/java/cz/o2/proxima/direct/blob/BlobLogReaderTest.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/cassandra/CassandraLogReader.java
- direct/io-cassandra/src/test/java/cz/o2/proxima/direct/cassandra/CassandraDBAccessorTest.java
- direct/io-hadoop/src/main/java/cz/o2/proxima/direct/hadoop/HadoopBatchLogReader.java
- direct/io-hadoop/src/test/java/cz/o2/proxima/direct/hadoop/HadoopStorageTest.java
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/HBaseLogReader.java
- direct/io-hbase-bindings/src/test/java/cz/o2/proxima/direct/hbase/HBaseLogReaderTest.java
- flink/core/src/main/java/cz/o2/proxima/flink/core/batch/OffsetTrackingBatchLogReader.java
- flink/core/src/test/java/cz/o2/proxima/flink/core/batch/OffsetTrackingBatchLogReaderTest.java
- flink/pom.xml
- flink/utils/license-header-spotless.txt
- flink/utils/license-header.txt
- flink/utils/pom.xml
- flink/utils/src/main/java/cz/o2/proxima/flink/utils/FlinkGlobalWatermarkTracker.java
- flink/utils/src/test/java/cz/o2/proxima/flink/utils/FlinkGlobalWatermarkTrackerTest.java
Closes O2-Czech-Republic#295
Closes O2-Czech-Republic#296
> [proxima-flink-utils] O2-Czech-Republic#295 add FlinkGlobalWatermarkTracker

- direct/core/src/main/java/cz/o2/proxima/direct/transform/TransformationObserver.java
- direct/core/src/test/java/cz/o2/proxima/direct/transform/TransformationObserverTest.java
> [proxima-direct-core] O2-Czech-Republic#299 handle transaction rejected in transforms

- .github/workflows/mvn.sh
- direct/io-bigtable/pom.xml
- direct/io-bigtable/src/main/java/cz/o2/proxima/direct/bigtable/BigTableStorage.java
- direct/io-hadoop/pom.xml
- direct/io-hbase-bindings/pom.xml
- direct/io-hbase-bindings/src/main/java/cz/o2/proxima/direct/hbase/HBaseWriter.java
- direct/io-hbase-bindings/src/test/java/cz/o2/proxima/direct/hbase/HBaseLogReaderTest.java
- direct/io-hbase-bindings/src/test/resources/log4j2.properties
- direct/io-hbase/pom.xml
- direct/io-hdfs/pom.xml
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptorTest.java
- direct/pom.xml
- example/model/pom.xml
- example/tools/pom.xml
- pom.xml
> Bump hbase to 2.5

- direct/core/src/main/java/cz/o2/proxima/direct/core/randomaccess/RandomAccessReader.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/storage/InMemStorage.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/storage/InMemStorageTest.java
- direct/ingest-server/src/main/java/cz/o2/proxima/direct/server/RetrieveService.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/RetrieveServiceTest.java
> [proxima-direct] O2-Czech-Republic#310 enhance prefix listing semantics

- beam/core/build.gradle
- beam/core/src/main/java/cz/o2/proxima/beam/core/BeamDataOperator.java
- beam/core/src/main/java/cz/o2/proxima/beam/core/direct/io/BlockingQueueLogObserver.java
- beam/core/src/test/java/cz/o2/proxima/beam/core/direct/io/BlockingQueueLogObserverTest.java
- beam/tools/src/test/java/cz/o2/proxima/beam/tools/groovy/BeamStreamTest.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/batch/BatchLogObserver.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/batch/TerminationContext.java
- direct/io-pubsub/module/src/main/java/cz/o2/proxima/direct/io/pubsub/PubSubReader.java
> [proxima-direct-core] [proxima-beam-core] O2-Czech-Republic#313 fix deadlock in BatchLogRead during shutdown

- direct/ingest-server/src/main/java/cz/o2/proxima/direct/server/RetrieveService.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/IngestServerTest.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/IngestServiceTest.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/RetrieveServiceTest.java
- direct/ingest-server/src/test/resources/test-ingest-server.conf
- direct/rpc/src/main/proto/rpc.proto
> [proxima-direct-rpc-server] O2-Czech-Republic#315 implement scan in ingest server

- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> [proxima-direct-transaction-manager] O2-Czech-Republic#320 reject transactions with multiple seqIds for same KeyAttribute

- core/src/main/java/cz/o2/proxima/core/metrics/ApproxPercentileMetric.java
- core/src/main/java/cz/o2/proxima/core/metrics/TimeAveragingMetric.java
- core/src/test/java/cz/o2/proxima/core/metrics/ApproxPercentileMetricTest.java
- core/src/test/java/cz/o2/proxima/core/metrics/TimeAveragingMetricTest.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/transaction/TransactionsTest.java
- direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/KafkaAccessor.java
- direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/KafkaLogReader.java
- direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/OffsetCommitter.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/io/kafka/OffsetCommitterTest.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/Metrics.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverFactory.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionManagerServer.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT_Large.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> 321 transaction manager metrics

- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionValidatorTest.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
* [proxima-transaction-manager] remove future updates from transaction update check
> [proxima-direct-core] handle TransactionRejectedException in validator

- core/src/main/java/cz/o2/proxima/core/transaction/Commit.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/ClientTransactionManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionResourceManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transform/TransformationObserver.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionResourceManagerTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionUniqueConstraintValidator.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionValidatorTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionalCachedViewTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriterTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transform/TransformationObserverTest.java
- direct/core/src/test/resources/log4j2.properties
- direct/ingest-server/src/main/java/cz/o2/proxima/direct/server/transaction/TransactionContext.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT_Large.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> [proxima-direct-core] #323 asynchronous transaction update

- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/ThreadPooledObserver.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionResourceManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/storage/InMemStorage.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriterTest.java
- direct/ingest-server/build.gradle
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/transaction/TransactionsTest.java
- direct/ingest-server/src/test/resources/log4j2.properties
- direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/KafkaLogReader.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
> [proxima-direct-transaction-manager] #324 wait for watermark before commit

- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/ServerTransactionManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionMonitoringPolicy.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionResourceManager.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TestMonitoringPolicy.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> [proxima-direct-transaction-manager] #326 add TransactionMonitoringPolicy

- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
> [proxima-direct-transaction-manager] #327 allow transaction reopen after abort

- core/src/main/java/cz/o2/proxima/core/transaction/Commit.java
- core/src/main/java/cz/o2/proxima/core/transaction/KeyAttribute.java
- core/src/main/java/cz/o2/proxima/core/transaction/Request.java
- core/src/main/java/cz/o2/proxima/core/transaction/State.java
- core/src/test/java/cz/o2/proxima/core/transaction/CommitTest.java
- core/src/test/java/cz/o2/proxima/core/transaction/KeyAttributeTest.java
- core/src/test/java/cz/o2/proxima/core/transaction/StateTest.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/ClientTransactionManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionCommitTransformation.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionResourceManager.java
- direct/core/src/main/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriter.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionCommitTransformationTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionResourceManagerTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionValidatorTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionalCachedViewTest.java
- direct/core/src/test/java/cz/o2/proxima/direct/core/transaction/TransactionalOnlineAttributeWriterTest.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/transaction/TransactionsTest.java
- direct/transaction-manager/src/main/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserver.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionIT_Large.java
- direct/transaction-manager/src/test/java/cz/o2/proxima/direct/transaction/manager/TransactionLogObserverTest.java
- scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactory.java
- scheme/proto/src/main/proto/transactions.proto
- scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoSerializerFactoryTest.java
> [proxima-direct-transaction] #329 commit via replication coordinator

- direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/serializer/ValueAsStringSerializer.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/io/kafka/serializer/ValueAsStringSerializerTest.java
> [proxima-direct-io-kafka] #334 add ValueAsStringSerializer

- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/io/cassandra/CassandraRandomReader.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/io/cassandra/CqlFactory.java
- direct/io-cassandra/src/main/java/cz/o2/proxima/direct/io/cassandra/DefaultCqlFactory.java
- direct/io-cassandra/src/test/java/cz/o2/proxima/direct/io/cassandra/DefaultCqlFactoryTest.java
> [proxima-direct-io-cassandra] #331 fix deserialization of values written with serializer v2

- direct/ingest-client/src/test/java/cz/o2/proxima/direct/client/IngestClientTest.java
- direct/ingest-server/src/main/java/cz/o2/proxima/direct/server/RetrieveService.java
- direct/ingest-server/src/test/java/cz/o2/proxima/direct/server/RetrieveServiceTest.java
- rpc/src/main/proto/rpc.proto
> Bulk scanning

- beam/core/src/main/java/cz/o2/proxima/beam/util/FilterLatecomers.java
- beam/core/src/main/java/cz/o2/proxima/beam/util/WatermarkShift.java
- beam/core/src/test/java/cz/o2/proxima/beam/util/FilterLatecomersTest.java
- beam/core/src/test/java/cz/o2/proxima/beam/util/WatermarkShiftTest.java
> watermark shift

- beam/core/src/main/java/cz/o2/proxima/beam/core/transforms/CalendarWindows.java
- beam/core/src/test/java/cz/o2/proxima/beam/core/transforms/CalendarWindowsTest.java
- beam/tools/src/main/java/cz/o2/proxima/beam/tools/groovy/BeamStream.java
This reverts commit 3a5509236dbc315a698d62e9cfc13ce7f863c7ea.
> Revert "[proxima-beam-core] remove fork of CalendarWindows"

- direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/KafkaLogReader.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/io/kafka/LocalKafkaCommitLogDescriptor.java
- direct/io-kafka/src/test/java/cz/o2/proxima/direct/io/kafka/LocalKafkaCommitLogDescriptorTest.java
> [proxima-direct-io-kafka] #350 check endOffsets to mark partition idle
