datadrivencz/proxima-platform

.gitignore
cassandra/src/test/java/cz/o2/proxima/storage/cassandra/CassandraDBAccessorTest.java
cassandra/src/test/java/cz/o2/proxima/storage/cassandra/DefaultCQLFactoryTest.java
cassandra/src/test/java/cz/o2/proxima/storage/cassandra/TransformingCQLFactoryTest.java
core/src/main/java/cz/o2/proxima/repository/AttributeDescriptor.java
core/src/main/java/cz/o2/proxima/repository/AttributeDescriptorBase.java
core/src/main/java/cz/o2/proxima/repository/AttributeFamilyDescriptor.java
core/src/main/java/cz/o2/proxima/repository/AttributeFamilyProxyDescriptor.java
core/src/main/java/cz/o2/proxima/repository/AttributeProxyDescriptorImpl.java
core/src/main/java/cz/o2/proxima/repository/EntityDescriptor.java
core/src/main/java/cz/o2/proxima/repository/EntityDescriptorImpl.java
core/src/main/java/cz/o2/proxima/repository/ProxyTransform.java
core/src/main/java/cz/o2/proxima/repository/Repository.java
core/src/main/java/cz/o2/proxima/storage/AccessType.java
core/src/test/java/cz/o2/proxima/repository/PartitionedViewTest.java
core/src/test/java/cz/o2/proxima/repository/RepositoryTest.java
core/src/test/java/cz/o2/proxima/transform/EventTransform.java
core/src/test/resources/reference.conf
kafka/src/test/java/cz/o2/proxima/storage/kafka/LocalKafkaCommitLogDescriptorTest.java
maven/src/main/resources/java-source.ftlh
server/src/main/java/cz/o2/proxima/server/IngestServer.java
server/src/test/java/cz/o2/proxima/server/IngestServiceTest.java
tools/src/main/java/cz/o2/proxima/tools/groovy/Console.java
tools/src/main/java/cz/o2/proxima/tools/io/BatchSource.java
tools/src/main/java/cz/o2/proxima/tools/io/ConsoleRandomReader.java

This is a draft of introducing virtual proxy attributes to entities. The proxy attribute is not physically existing in storage and is built up when accessing it (read, write, delete). For now, this functionality is very limited, but unfortunately that's all what I need now.

 [proxima-core] #30 add proxy attributes to entities

---

direct/io-gcloud-storage/pom.xml
direct/io-gcloud-storage/src/main/java/cz/o2/proxima/direct/gcloud/storage/BulkGCloudStorageWriter.java
direct/io-gcloud-storage/src/test/java/cz/o2/proxima/direct/gcloud/storage/BulkGCloudStorageWriterTest.java

Tests leave a lot of folders like /tmp/bulk-cloud-storage-3cf95540-cad5-420a-8799-effde9e3bd5a
I'm not sure about that shading change, please check it.

Fixed resource leak in tests and shading guava

---

direct/io-pubsub/README.md
direct/io-pubsub/src/main/java/cz/o2/proxima/direct/pubsub/PubSubAccessor.java
direct/io-pubsub/src/main/java/cz/o2/proxima/direct/pubsub/PubSubReader.java
direct/io-pubsub/src/test/java/cz/o2/proxima/direct/pubsub/PubSubReaderTest.java

- added topic check
- change default value for pubsub.subscription.auto-create - now true
- change default value for pubsub.subscription.ack-deadline - now 600
- added small part of documentation into README

Allow update pubsub.subscription.ack-deadline in io-pubsub

---

direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/Utils.java

hotfix for
```
2020-03-05 16:20:53,744 ERROR cz.o2.proxima.direct.kafka.KafkaLogReader                     - Error processing consumer null
java.lang.IllegalArgumentException: seek offset must not be a negative number
at cz.o2.proxima.kafka.shaded.org.apache.kafka.clients.consumer.KafkaConsumer.seek(KafkaConsumer.java:1560)
at cz.o2.proxima.direct.kafka.Utils.lambda$seekToOffsets$0(Utils.java:50)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at cz.o2.proxima.direct.kafka.Utils.seekToOffsets(Utils.java:46)
at cz.o2.proxima.direct.kafka.KafkaLogReader.createConsumer(KafkaLogReader.java:633)
at cz.o2.proxima.direct.kafka.KafkaLogReader.lambda$submitConsumerWithObserver$4(KafkaLogReader.java:342)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at …
```

[io-kafka] Do not seek to negative offsets.

---

direct/io-blob/src/main/java/cz/o2/proxima/direct/blob/BlobLogObservable.java

Original output like
```
Starting to observe partition cz.o2.proxima.direct.blob.BlobLogObservable$BulkStoragePartition@99491d5
```
is not so useful, this looks better
```
Starting to observe partition BulkStoragePartition{id=0, size=201, minTimestamp=0, maxTimestamp=3600000}
```

[direct-io-blob]: improve logging in BlobLogObservable

---

direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaAccessor.java

```
The configuration 'kafka.max.poll.records' was supplied but isn't a known config.
at cz.o2.proxima.kafka.shaded.org.apache.kafka.common.config.AbstractConfig.logUnused(AbstractConfig.java:355)
```

[io-kafka] Fix max.poll.records warning.

---

utils-zookeeper/src/main/java/cz/o2/proxima/utils/zookeeper/ZKGlobalWatermarkTracker.java
utils-zookeeper/src/test/java/cz/o2/proxima/utils/zookeeper/ZKGlobalWatermarkTrackerTest.java

In current state Proxima allows to define only single Zookeeper host even when Zookeeper supports list of hosts separated by comma. This modification should enable to define list of Zookeeper hosts.

Modified to enable list of zookeeper hosts.

---

core/src/main/java/cz/o2/proxima/repository/ConfigRepository.java
core/src/main/java/cz/o2/proxima/storage/internal/AbstractDataAccessorFactory.java
core/src/test/java/cz/o2/proxima/repository/ConfigRepositoryTest.java

User will now get exception like:
'Attribute name in entity user must be proxy or contains scheme definition.'
when attribute doesn't contains scheme or proxy definition

[proxima-core] Prevent typos in attribute definition.

---

beam/core/src/main/java/cz/o2/proxima/beam/core/BeamDataOperator.java
core/src/main/java/cz/o2/proxima/storage/internal/AbstractDataAccessorFactory.java
core/src/test/java/cz/o2/proxima/storage/internal/AbstractDataAccessorFactoryTest.java
direct/core/src/main/java/cz/o2/proxima/direct/core/DirectDataOperator.java
direct/core/src/test/java/cz/o2/proxima/direct/core/DirectDataOperatorTest.java
direct/core/src/test/java/cz/o2/proxima/direct/storage/InMemStorage.java
pom.xml

`DataAccessor` should have access to `AttributeFamilyDescriptor` not just `EntityDescriptor` and configuration.

Allow access to AttributeFamily in DataAccessor

---

core/pom.xml
core/src/main/java/cz/o2/proxima/repository/EntityDescriptor.java
core/src/test/java/cz/o2/proxima/repository/EntityDescriptorBuilderTest.java

Warning: this is possible breaking change where now we disallow to have
wildcard and normal attribute with same name.
This will not be valid anymore:
```
entities {
entitiName {
attributes {
attribute: {...}
"attribute.*": {...}
}
}
}
```

Check attribute names in entity for possible duplicates with wildcards

---

core/src/test/java/cz/o2/proxima/scheme/AlwaysFailSchemeParser.java
core/src/test/java/cz/o2/proxima/util/TestUtils.java
direct/io-blob/src/main/java/cz/o2/proxima/direct/blob/BlobStorageAccessor.java
direct/io-blob/src/test/java/cz/o2/proxima/direct/blob/BlobLogReaderTest.java
direct/io-blob/src/test/java/cz/o2/proxima/direct/blob/BlobStorageAccessorTest.java
direct/io-blob/src/test/java/cz/o2/proxima/direct/blob/BulkBlobWriterTest.java
direct/io-blob/src/test/java/cz/o2/proxima/direct/blob/TestBlobStorageAccessor.java
direct/io-bulkfs/src/main/java/cz/o2/proxima/direct/bulk/FileFormat.java
direct/io-bulkfs/src/test/java/cz/o2/proxima/direct/bulk/BinaryBlobFormatTest.java
direct/io-gcloud-storage/src/main/java/cz/o2/proxima/direct/gcloud/storage/GCloudStorageAccessor.java
direct/io-gcloud-storage/src/main/java/cz/o2/proxima/direct/gcloud/storage/GCloudStorageDescriptor.java
direct/io-gcloud-storage/src/test/java/cz/o2/proxima/direct/gcloud/storage/GCloudFileSystemTest.java
direct/io-gcloud-storage/src/test/java/cz/o2/proxima/direct/gcloud/storage/GCloudLogReaderTest.java
direct/io-gcloud-storage/src/test/java/cz/o2/proxima/direct/gcloud/storage/GCloudStorageAccessorTest.java
direct/io-gcloud-storage/src/test/java/cz/o2/proxima/direct/gcloud/storage/GCloudStorageDescriptorTest.java
direct/io-s3/pom.xml
direct/io-s3/src/main/java/cz/o2/proxima/direct/s3/S3Accessor.java
direct/io-s3/src/main/java/cz/o2/proxima/direct/s3/S3StorageDescriptor.java
direct/io-s3/src/test/java/cz/o2/proxima/direct/s3/S3AccessorTest.java
direct/io-s3/src/test/java/cz/o2/proxima/direct/s3/S3BlobPathTest.java
direct/io-s3/src/test/java/cz/o2/proxima/direct/s3/S3FileSystemTest.java

* Migrage io-s3, io-gcloud and io-bulkfs  api to be created via AttributeFamilyDescriptor
* Added setup method into `FileFormat`
* `org.apache.http.` needs to be shaded in io-s3
* Implement returning schema from `AlwaysFailSchemeParser`

Migrate bulk IOs to accept AttributeFamilyDescriptor + fix shading

---

utils-zookeeper/src/test/java/cz/o2/proxima/utils/zookeeper/ZKGlobalWatermarkTrackerTest.java

We can disable admin server in Zookeeper started in tests as we are not
using it. Starting admin server just add some overhead and it sometimes
leads to flaky timeouts.
Also removed this ClassNotFoundException
```
java.lang.NoClassDefFoundError: org/eclipse/jetty/security/SecurityHandler
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.apache.zookeeper.server.admin.AdminServerFactory.createAdminServer(AdminServerFactory.java:43)
at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:151)
at cz.o2.proxima.utils.zookeeper.ZKGlobalWatermarkTrackerTest.lambda$setupGlobal$0(ZKGlobalWatermarkTrackerTest.java:104)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at …
```

[proxima-utils-zookeeper]: Do not try to load JettyAdminServer in tests

---

direct/core/src/main/java/cz/o2/proxima/direct/commitlog/LogObservers.java
direct/core/src/main/java/cz/o2/proxima/direct/commitlog/RetryableLogObserver.java
direct/core/src/test/java/cz/o2/proxima/direct/commitlog/CommitLogReaderTest.java
direct/core/src/test/java/cz/o2/proxima/direct/commitlog/RetryableLogObserverTest.java
direct/ingest-server/src/main/java/cz/o2/proxima/server/ReplicationController.java
direct/ingest-server/src/main/java/cz/o2/proxima/server/TransformationObserver.java
direct/ingest-server/src/test/java/cz/o2/proxima/server/ReplicationControllerTest.java
direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/LocalKafkaCommitLogDescriptorTest.java

Introduce LogObserver.withNumRetried(Exceptions|Throwables).

[proxima-direct-core] Remove RetryableLogObserver public API

---

direct/pom.xml

In current situation io-bigtable use jdk8 io-hbase which isn't build during CI run. This commit bring it back as https://github.com/datadrivencz/proxima-platform/pull/510 removes it.
We need to rebase this after  https://github.com/datadrivencz/proxima-platform/pull/510 is merged - Until that marked as WIP.

Return bigtable to jdk11 profile

---

scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/utils/ProtoUtils.java
scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoMessageValueAccessorTest.java
scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/utils/ProtoUtilsTest.java
scheme/proto/src/test/proto/scheme.proto

Fix exceptions like
```
java.lang.IllegalStateException: Recursive update
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763)
at cz.o2.proxima.scheme.proto.utils.ProtoUtils.convertField(ProtoUtils.java:117)
at cz.o2.proxima.scheme.proto.utils.ProtoUtils.lambda$convertProtoMessage$0(ProtoUtils.java:65)
```

Fix cache usage in proto schema extraction to avoid Recursive update

---

direct/io-kafka/pom.xml

Moving from test scope to provided because of failing snapshot build.

[proxima-direct-io-kafka] exclude IT dependencies from test-jar

---

scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/ProtoMessageValueAccessor.java
scheme/proto/src/main/java/cz/o2/proxima/scheme/proto/utils/ProtoUtils.java
scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/ProtoMessageValueAccessorTest.java
scheme/proto/src/test/java/cz/o2/proxima/scheme/proto/utils/ProtoUtilsTest.java
scheme/proto/src/test/proto/scheme.proto

Protobufs returns always default values for scalar types
(for example: bool field => false) and we need to use message wrapper in case you need to have `null`
value.
For this purpose protobufs create wrapper messages ("google/protobuf/wrappers.proto") for scalar types.
As we support `null` values directly, we can map this known wrappers into scalar types which simplify work with this structures.
For example `google.protobuf.BoolValue` can be mapped as `SchemaDescriptors.booleans()` etc.

[proxima-scheme-proto]: Protobufs wrappers mapped as scalar types

---

direct/io-s3/src/main/java/cz/o2/proxima/direct/s3/S3Client.java
direct/io-s3/src/test/java/cz/o2/proxima/direct/s3/S3ClientTest.java

Fix situation when s3 endpoint is just hostname/ip without schema.

[io-s3] Custom S3 endpoint need not be valid URI

---

direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaAccessor.java
direct/io-kafka/src/main/java/cz/o2/proxima/direct/kafka/KafkaWriter.java
direct/io-kafka/src/test/java/cz/o2/proxima/direct/kafka/KafkaAccessorTest.java

Not related:
- Added check + test for state commitlog on regexp specified topics.
- Added check for possible NPE in log for kafka write callback

[io-kafka] Allow to specify ack and batch size for kafka producer

---

direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/KafkaAccessor.java
direct/io-kafka/src/main/java/cz/o2/proxima/direct/io/kafka/KafkaStreamElement.java
direct/io-kafka/src/test/java/cz/o2/proxima/direct/io/kafka/KafkaLogReaderIT.java

Store and restore origin StreamElement#uuid in case of no seqId so it can be stable between multiple storages.

[io-kafka] keep source StreamElement#uuid in case of no seqId

---

direct/core/src/test/java/cz/o2/proxima/direct/core/util/ReplicationRunner.java

[proxima-direct-core] #318 filter target attributes in test replication controller

---

.github/workflows/gradle.sh
beam/core/src/main/java/cz/o2/proxima/beam/util/state/ExternalStateExpander.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/FlushTimerParameterExpander.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/MethodCallUtils.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/OnWindowParameterExpander.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/ProcessElementParameterExpander.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/StateOrInput.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/StateValue.java
beam/core/src/main/java/cz/o2/proxima/beam/util/state/TypeId.java
beam/core/src/test/java/cz/o2/proxima/beam/util/state/ExternalStateExpanderTest.java
beam/core/src/test/java/cz/o2/proxima/beam/util/state/MethodCallUtilsTest.java
beam/core/src/test/java/cz/o2/proxima/beam/util/state/TypeIdTest.java
core/src/main/java/cz/o2/proxima/core/util/SerializableScopedValue.java
core/src/test/java/cz/o2/proxima/core/util/SerializableScopedValueTest.java

339 external state expander

---

beam/core/src/main/java/cz/o2/proxima/beam/util/FilterLatecomers.java
beam/core/src/test/java/cz/o2/proxima/beam/util/FilterLatecomersTest.java

[proxima-beam-core] #344 add FilterLatecomers transform
